services:
  demo:
    # image: python:3.12-alpine
    build: 
      context: .
      dockerfile: dockerfile
    container_name: demo
    ports:
      - "8080:8080"
    volumes:
      - './:/webapp'
    network_mode: bridge
    tty: true